import type { Metadata } from 'next';
import React from 'react';
import Link from 'next/link';
import { ArrowLeft, FileText, Scale, Shield, AlertTriangle, Users, Ban, RefreshCw, Globe, Gavel } from 'lucide-react';
import styles from '../privacy/PrivacyPolicy.module.css';

export const metadata: Metadata = {
  title: 'Terms of Service',
  description: 'Scanterity Terms of Service — Read our terms governing the use of Scanterity forensic plagiarism detection, AI content analysis, and document scanning services.',
  alternates: { canonical: '/terms' },
  openGraph: {
    title: 'Terms of Service | Scanterity',
    description: 'Terms governing the use of Scanterity forensic plagiarism detection services.',
    url: 'https://scanterity.com/terms',
  },
};

export default function TermsOfService() {
  return (
    <div className={styles.container}>
      <div className={styles.contentWrapper}>
        <div className={styles.backButtonContainer}>
          <Link href="/" className={styles.backButton}>
            <ArrowLeft size={18} strokeWidth={2.5} />
            Back to Scanner
          </Link>
        </div>

        <div className={styles.header}>
          <h1 className={styles.title}>Terms of Service</h1>
          <div className={styles.lastUpdated}>Effective: August 18, 2026</div>
        </div>

        <article className={styles.document}>
          <div className={styles.highlight}>
            <Scale className={styles.highlightIcon} size={24} strokeWidth={2.5} />
            <p style={{ margin: 0 }}>
              <strong>Summary:</strong> By using Scanterity, you agree to these terms. We provide forensic plagiarism detection tools &ldquo;as is.&rdquo; You retain full ownership of all content you scan. We do not store, sell, or claim rights over your documents.
            </p>
          </div>

          {/* Section 1 */}
          <section className={styles.section}>
            <h2 className={styles.sectionTitle}>
              <div className={styles.sectionIcon}><FileText size={18} strokeWidth={2.5} /></div>
              1. Acceptance of Terms
            </h2>
            <p className={styles.text}>
              These Terms of Service (&ldquo;Terms&rdquo;) constitute a legally binding agreement between you (&ldquo;User,&rdquo; &ldquo;you,&rdquo; or &ldquo;your&rdquo;) and Scanterity Forensic Systems (&ldquo;Scanterity,&rdquo; &ldquo;we,&rdquo; &ldquo;us,&rdquo; or &ldquo;our&rdquo;). By accessing or using the Scanterity platform, including all associated websites, applications, APIs, and services (collectively, the &ldquo;Service&rdquo;), you acknowledge that you have read, understood, and agree to be bound by these Terms, our <Link href="/privacy" style={{ color: 'var(--nb-purple)', fontWeight: 700 }}>Privacy Policy</Link>, and our <Link href="/compliance" style={{ color: 'var(--nb-purple)', fontWeight: 700 }}>GDPR &amp; Compliance Policy</Link>.
            </p>
            <p className={styles.text}>
              If you do not agree to these Terms in their entirety, you must not access or use the Service. If you are using the Service on behalf of an organization, you represent and warrant that you have the authority to bind that organization to these Terms.
            </p>
          </section>

          {/* Section 2 */}
          <section className={styles.section}>
            <h2 className={styles.sectionTitle}>
              <div className={styles.sectionIcon}><Shield size={18} strokeWidth={2.5} /></div>
              2. Description of Service
            </h2>
            <p className={styles.text}>
              Scanterity provides forensic plagiarism detection, AI-generated content analysis, and document originality verification services. The Service operates through a multi-algorithm engine that analyzes submitted text against publicly accessible online sources. Key capabilities include:
            </p>
            <ul className={styles.list}>
              <li className={styles.listItem}><strong>Exact Match Detection:</strong> Identification of verbatim content duplication against web-accessible sources.</li>
              <li className={styles.listItem}><strong>Paraphrase Detection:</strong> Semantic analysis to identify rephrased or restructured content derived from existing sources.</li>
              <li className={styles.listItem}><strong>AI Content Detection:</strong> Probabilistic analysis of text patterns to identify content likely generated by large language models (LLMs).</li>
              <li className={styles.listItem}><strong>Forensic Reporting:</strong> Generation of comprehensive PDF reports with source attributions, confidence scores, and algorithmic breakdowns.</li>
            </ul>
            <p className={styles.text}>
              The Service is intended as an analytical tool to assist in originality assessment. Results should be interpreted by qualified individuals and should not be the sole basis for academic, legal, or employment decisions.
            </p>
          </section>

          {/* Section 3 */}
          <section className={styles.section}>
            <h2 className={styles.sectionTitle}>
              <div className={styles.sectionIcon}><Users size={18} strokeWidth={2.5} /></div>
              3. User Obligations &amp; Acceptable Use
            </h2>
            <p className={styles.text}>
              You agree to use the Service only for lawful purposes and in compliance with all applicable local, national, and international laws and regulations. You shall NOT:
            </p>
            <ul className={styles.list}>
              <li className={styles.listItem}>Submit content that you do not have the legal right to scan or analyze.</li>
              <li className={styles.listItem}>Use the Service to facilitate academic fraud, content theft, or any other form of intellectual dishonesty.</li>
              <li className={styles.listItem}>Attempt to reverse-engineer, decompile, disassemble, or otherwise extract the source code or algorithms of the Service.</li>
              <li className={styles.listItem}>Use automated scripts, bots, or scrapers to access the Service in a manner that exceeds reasonable personal or organizational use.</li>
              <li className={styles.listItem}>Interfere with, disrupt, or impose an unreasonable burden on the Service infrastructure.</li>
              <li className={styles.listItem}>Resell, sublicense, or redistribute the Service or its outputs without prior written consent.</li>
              <li className={styles.listItem}>Submit content containing malware, viruses, or other harmful code.</li>
            </ul>
            <p className={styles.text}>
              We reserve the right to suspend or terminate access for any user who violates these obligations, with or without prior notice.
            </p>
          </section>

          {/* Section 4 */}
          <section className={styles.section}>
            <h2 className={styles.sectionTitle}>
              <div className={styles.sectionIcon}><FileText size={18} strokeWidth={2.5} /></div>
              4. Intellectual Property &amp; Content Ownership
            </h2>
            <p className={styles.text}>
              <strong>Your Content:</strong> You retain all ownership rights, copyright, and intellectual property rights in and to any content you submit to the Service for analysis. Scanterity does not claim any ownership, license, or rights over your submitted content. Content is processed ephemerally in volatile memory (RAM) and is not persistently stored, indexed, or added to any database.
            </p>
            <p className={styles.text}>
              <strong>Our Platform:</strong> The Scanterity platform, including its algorithms, user interface, branding, source code, documentation, and all associated intellectual property, is owned exclusively by Scanterity Forensic Systems and is protected by applicable copyright, trademark, and trade secret laws. Unauthorized reproduction, modification, or distribution of any part of the platform is strictly prohibited.
            </p>
            <p className={styles.text}>
              <strong>Scan Reports:</strong> The forensic reports generated by the Service are derivative works based on your input and our algorithms. You are granted a non-exclusive, royalty-free license to use, distribute, and reproduce these reports for your internal purposes.
            </p>
          </section>

          {/* Section 5 */}
          <section className={styles.section}>
            <h2 className={styles.sectionTitle}>
              <div className={styles.sectionIcon}><AlertTriangle size={18} strokeWidth={2.5} /></div>
              5. Disclaimers &amp; Limitation of Liability
            </h2>
            <p className={styles.text}>
              THE SERVICE IS PROVIDED &ldquo;AS IS&rdquo; AND &ldquo;AS AVAILABLE&rdquo; WITHOUT WARRANTIES OF ANY KIND, WHETHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, OR ACCURACY.
            </p>
            <ul className={styles.list}>
              <li className={styles.listItem}><strong>No Guarantee of Accuracy:</strong> Scanterity uses probabilistic algorithms and heuristic analysis. Results may contain false positives or false negatives. We do not guarantee 100% detection accuracy.</li>
              <li className={styles.listItem}><strong>Not Legal Advice:</strong> Scan results do not constitute legal opinions, definitive proof of plagiarism, or certification of originality. They are analytical tools to assist human judgment.</li>
              <li className={styles.listItem}><strong>AI Detection Limitations:</strong> AI content detection is inherently probabilistic and may not accurately identify all AI-generated content, particularly after human editing.</li>
            </ul>
            <p className={styles.text}>
              TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL SCANTERITY, ITS OFFICERS, DIRECTORS, EMPLOYEES, AGENTS, OR AFFILIATES BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO LOSS OF PROFITS, DATA, USE, GOODWILL, OR OTHER INTANGIBLE LOSSES, ARISING OUT OF OR RELATING TO YOUR USE OF OR INABILITY TO USE THE SERVICE, REGARDLESS OF THE THEORY OF LIABILITY.
            </p>
            <p className={styles.text}>
              OUR TOTAL AGGREGATE LIABILITY FOR ALL CLAIMS ARISING OUT OF OR RELATING TO THESE TERMS OR THE SERVICE SHALL NOT EXCEED THE GREATER OF (A) THE AMOUNT YOU PAID TO SCANTERITY IN THE TWELVE (12) MONTHS PRECEDING THE CLAIM, OR (B) ONE HUNDRED U.S. DOLLARS ($100).
            </p>
          </section>

          {/* Section 6 */}
          <section className={styles.section}>
            <h2 className={styles.sectionTitle}>
              <div className={styles.sectionIcon}><Ban size={18} strokeWidth={2.5} /></div>
              6. Indemnification
            </h2>
            <p className={styles.text}>
              You agree to indemnify, defend, and hold harmless Scanterity and its officers, directors, employees, agents, and affiliates from and against any and all claims, liabilities, damages, losses, costs, and expenses (including reasonable attorneys&rsquo; fees) arising out of or relating to: (a) your use of the Service; (b) your violation of these Terms; (c) your violation of any rights of a third party; or (d) any content you submit to the Service.
            </p>
          </section>

          {/* Section 7 */}
          <section className={styles.section}>
            <h2 className={styles.sectionTitle}>
              <div className={styles.sectionIcon}><RefreshCw size={18} strokeWidth={2.5} /></div>
              7. Termination
            </h2>
            <p className={styles.text}>
              We may suspend or terminate your access to the Service at any time, with or without cause, and with or without notice. Upon termination, your right to use the Service immediately ceases. Sections 4 (Intellectual Property), 5 (Disclaimers), 6 (Indemnification), and 9 (Governing Law) shall survive termination.
            </p>
            <p className={styles.text}>
              You may discontinue your use of the Service at any time. If you have a paid subscription, cancellation policies and refund eligibility will be governed by the specific terms of your subscription plan.
            </p>
          </section>

          {/* Section 8 */}
          <section className={styles.section}>
            <h2 className={styles.sectionTitle}>
              <div className={styles.sectionIcon}><RefreshCw size={18} strokeWidth={2.5} /></div>
              8. Modifications to Terms
            </h2>
            <p className={styles.text}>
              We reserve the right to modify these Terms at any time. Material changes will be communicated via email notification (for registered users) or a prominent notice on the Service at least thirty (30) days before the changes take effect. Your continued use of the Service after the effective date of any modifications constitutes your acceptance of the revised Terms. If you do not agree to the revised Terms, you must discontinue use of the Service.
            </p>
          </section>

          {/* Section 9 */}
          <section className={styles.section}>
            <h2 className={styles.sectionTitle}>
              <div className={styles.sectionIcon}><Globe size={18} strokeWidth={2.5} /></div>
              9. Governing Law &amp; Dispute Resolution
            </h2>
            <p className={styles.text}>
              These Terms shall be governed by and construed in accordance with the laws of the State of Delaware, United States, without regard to its conflict of law provisions. For users in the European Economic Area (EEA), these Terms do not affect your rights under mandatory consumer protection laws of your country of residence.
            </p>
            <p className={styles.text}>
              Any dispute arising out of or relating to these Terms shall first be attempted to be resolved through good-faith negotiation. If negotiation fails, disputes shall be submitted to binding arbitration under the rules of the American Arbitration Association (AAA), except that either party may seek injunctive or equitable relief in a court of competent jurisdiction.
            </p>
          </section>

          {/* Section 10 */}
          <section className={styles.section}>
            <h2 className={styles.sectionTitle}>
              <div className={styles.sectionIcon}><Gavel size={18} strokeWidth={2.5} /></div>
              10. General Provisions
            </h2>
            <ul className={styles.list}>
              <li className={styles.listItem}><strong>Severability:</strong> If any provision of these Terms is held to be unenforceable, the remaining provisions shall continue in full force and effect.</li>
              <li className={styles.listItem}><strong>Waiver:</strong> Failure to enforce any right or provision of these Terms shall not constitute a waiver of such right or provision.</li>
              <li className={styles.listItem}><strong>Entire Agreement:</strong> These Terms, together with our Privacy Policy and Compliance Policy, constitute the entire agreement between you and Scanterity regarding the Service.</li>
              <li className={styles.listItem}><strong>Assignment:</strong> You may not assign or transfer these Terms without our prior written consent. We may assign our rights and obligations without restriction.</li>
              <li className={styles.listItem}><strong>Force Majeure:</strong> Scanterity shall not be liable for any failure or delay in performance resulting from circumstances beyond our reasonable control, including natural disasters, war, terrorism, pandemics, or government actions.</li>
            </ul>
          </section>

          {/* Contact */}
          <section className={styles.section}>
            <h2 className={styles.sectionTitle}>
              <div className={styles.sectionIcon}><FileText size={18} strokeWidth={2.5} /></div>
              11. Contact Information
            </h2>
            <p className={styles.text}>
              For questions regarding these Terms of Service, please contact us at:
            </p>
            <div className={styles.highlight}>
              <Shield className={styles.highlightIcon} size={24} strokeWidth={2.5} />
              <div style={{ margin: 0 }}>
                <strong>Scanterity Legal Department</strong><br />
                Email: <a href="mailto:hello@scanterity.com" style={{ color: 'var(--nb-purple)', fontWeight: 700 }}>hello@scanterity.com</a><br />
                Data Protection Officer: <a href="mailto:hello@scanterity.com" style={{ color: 'var(--nb-purple)', fontWeight: 700 }}>hello@scanterity.com</a>
              </div>
            </div>
          </section>
        </article>
      </div>
    </div>
  );
}
